# Ex 5.A NumPy Fundamentals

In [1]:
import numpy as np

## Array basics

In [2]:
fruits =['apple','bannana','cherry','date']

In [3]:
print(fruits)

['apple', 'bannana', 'cherry', 'date']


In [4]:
arr_1 =np.array(fruits)

In [5]:
print(arr_1)

['apple' 'bannana' 'cherry' 'date']


In [6]:
print(arr_1.dtype)

<U7


In [8]:
print(arr_2)

((10, 11, 12), (13, 14, 15))


In [19]:
arr_2 =np.array([(10,11,12),(13,14,15)])

In [20]:
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [16]:
(arr_2.T)

array([[10, 13],
       [11, 14],
       [12, 15]])

In [17]:
# It seems like it break up each tuple vertically.
# it only does it temporarily

In [18]:
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [26]:
arr_3 = np.array([(1,3,5),(2,4,6)])

    

In [27]:
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [30]:
arr_4 =np.array([arr_3[0,2],arr_3[1,1]])

In [31]:
print(arr_4)

[5 4]


In [32]:
arr_5 =np.ones((2,2,2))

In [33]:
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
