# Exercise 1.A NumPy: Manipulating Arrays

In [2]:
import numpy as np

## Looping Through Arrays,

In a new code cell, create a variable named arrA as a two-dimensional array
containing (11, 12, 13) and (14, 15, 16) then print arrA

In [2]:
arrA = np.array([[11,12,13],[14,15,16]])

In [3]:
print(arrA)

[[11 12 13]
 [14 15 16]]


In a new code cell, loop through the first dimension of arrA (i.e. for x in arrA) and
print each element multiplied by 2

In [6]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [8]:
for x in arrA:
    for y in x:
        print(y *2)

22
24
26
28
30
32


Description of last 2 cells between 1st and 2nd dimension
1st: we got x for each row and multiplied it by the row.
2nd: goes into each row and multiples it individually

Again loop through the second dimension of arrA (i.e. for y
in x), but this time, assign x*2 to a variable named loop_result. Add another line
of code to print loop_result, then add a comment to the cell to explain how/why
this result is different

In [15]:


for x in arrA:
    for y in x:
        loop_result = x*2
        print(loop_result)
        

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


In [16]:
print(loop_result)
# The results are different because we print it grabs the last line

[28 30 32]


## Joining and stacking Arrays

Create variable joined_array_1 and assign it the value of arrA concatenated
with arrA on axis=0 (the default axis). Print joined_array_1.

In [17]:
joined_array_1 = np.concatenate((arrA,arrA),axis=0)

In [18]:
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


Create variable joined_array_2 and assign it the value of arrA concatenated
with arrA on axis=1. Print joined_array_2.

In [15]:
joined_array_2 = np.concatenate((arrA,arrA),axis =1)

In [16]:
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


Create variable stacked_array_1 and assign it the value of joined_array_1
stacked with joined_array_1 on the default axis. Print stacked_array_1

In [21]:
stacked_array_1 = np.concatenate((joined_array_1,joined_array_1))

In [23]:
print(stacked_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


Create variable stacked_array_2 and assign it the value of joined_array_1
stacked with joined_array_2 on the default axis. What error message do you
get? Add a comment to the cell to explain the error that comes back.

In [26]:
stacked_array_2 = np.concatenate((joined_array_1,joined_array_2))
#The error occurs because the arrays do not have matching dimensions,basically one array has more and they cant properly line up

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 6

Create variable another_joined_array and assign it the value of
joined_array_1 concatenated with arrA. Print another_joined_array.

In [28]:
another_joined_array = np.concatenate((joined_array_1,arrA))

In [29]:
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


Create variable another_2 and again assign it the value of joined_array_1
concatenated with arrA, but this time on axis=1. What happens when you try to run
this? Add a comment to the cell to paraphrase the error message in your own
word

In [38]:
another_2 = np.concatenate((joined_array_1,arrA),axis=1)

# size of array needs to match exactly,one is size of 4 and other size 2 for index

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

Create a cell with three new variables (named as you choose). In each variable, use
either the hstack(), vstack(), or dstack() function to stack arrA with arrA.
Add a comment after each that explains what the function is doing. Print the results
of each variable

In [39]:
hor_stack =np.hstack((arrA,arrA))
#hstack() joins array horizontally ( side by side / adds columns)

In [40]:
print(hor_stack)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [41]:
vertical_stack = np.vstack((arrA,arrA))
#vstack() joins arrays vertically (top to bottom / adds rows)

In [42]:
print(vertical_stack)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [43]:
depth_stack = np.dstack((arrA,arrA))

#dstack() stacks arrays depth wise creates a 3d array

In [44]:
print(depth_stack)

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


# Splitting Arrays

Create variable splitsky and assign it the value of joined_array_1 split into 2.
Print the variable. Then add a comment to the cell to describe the result: how many
arrays? Of how many dimensions each?

In [45]:
splitsky = np.array_split(joined_array_1,2)

In [46]:
print(splitsky)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [47]:
#split into 2 seperate arrays
# each array still a 2 dimensional array

Create variable spliterino and assign it the value of joined_array_1 split
into 3. Print the variable. Then add a comment to the cell to describe the result: how
many arrays? Of how many dimensions each?

In [50]:
spliterino = np.array_split(joined_array_1,3)

In [51]:
print(spliterino)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


In [52]:
# 2 dimensions with 3 arrays in total

## Searching and replacing array values

n a code cell, create variable result_1. For the value of this variable, use where()
to find each even number within arrA (hint, you’ll need to write a condition using %
and ==). If the condition is met, print the value from arrA; if not met, print 'odd'.
Print result_1.

In [53]:
result_1 = np.where(arrA % 2 == 0,arrA,'odd')

In [54]:
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

Create variable arrB as a 2-D array including the values (7,6), (13,5), and (7,3).
Create another variable, arrB_sorted, and assign it the sorted value of arrB.
Print arrB_sorte

In [56]:
arrB = np.array ([[7,6],[13,5],[7,3]])

In [57]:
arrB_sorted = np.sort(arrB)

In [58]:
print(arrB_sorted)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [59]:
print(arrB)

[[ 7  6]
 [13  5]
 [ 7  3]]


In [60]:
z = arrB < 7

In [61]:
arrC = arrB[z]

In [62]:
print(arrC)

[6 5 3]


In [64]:
y = arrB > 7

In [65]:
arrD = arrB[y]

In [66]:
print(arrD)

[13]
