# Exercise 1.B Numpy Random

In [2]:
import numpy as np

## Generating Random Numbers

Create a variable named r_1 that contains a random set of integers between 1 and
20 with a size of 2 elements. Print r_1.

In [11]:
r_1 = np.random.randint(1,21,size =2)

In [ ]:
print(r_1()

[ 8 14]


Create a variable named r_2 that contains a random set of integers between 1 and
20 with a size of 1 row, 2 columns. Print r_2.

In [15]:
r_2 = np.random.randint(1,21,size=(1,2))

In [16]:
print(r_2)

[[15 17]]


Create a variable named r_3 that contains a random set of floats between 0 and 1
with a size of 2 rows, 1 columns. Print r_3

In [18]:
r_3 = np.random.rand(2,1)

In [19]:
print(r_3)

[[0.85778289]
 [0.19261389]]


Create a variable named r_4 that contains a random set of integers between 20
and 100 with a size of 4 rows, 5 columns. Print r_4.

In [21]:
r_4 = np.random.randint(20,101,size = (4,5))

Create a variable named r_5 that contains a random set of floats between 0 and 1
with a size of 4 rows, 5 columns. Print r_5

In [23]:
r_5 = np.random.rand(4,5)

In [24]:
print(r_5)

[[0.65160188 0.38776446 0.9606572  0.60816215 0.63683113]
 [0.71450058 0.55793229 0.03560635 0.82735218 0.84149397]
 [0.03375379 0.16960737 0.81138943 0.32144122 0.39617046]
 [0.88573102 0.79508764 0.65961534 0.81236105 0.47011821]]


# # Generating Random Choices from an Array

Create a variable named students and assign it a 1-D array containing the names
of 12 of your classmates.

In [18]:
students = np.array(["luis","sonia","cira","javi","kass","ang","Nova","zeus","nube","alexis","jp","sarah"])

Create a variable named call_on and use it to choose one random selection from
students. Print call_on.

In [9]:
call_on = np.random.choice(students,1)

In [11]:
print(call_on)

['alexis']


Create a variable named breakout_groups and use it to choose a random
sampling from students that is 3 rows, 4 columns in size. Prin

In [12]:
breakout_groups = np.random.choice(students, size = (3,4))

In [13]:
print(breakout_groups)

[['sonia' 'alexis' 'sarah' 'ang']
 ['ang' 'kass' 'nube' 'luis']
 ['cira' 'zeus' 'mario' 'alexis']]


 my opinion yes it does seperate them equally the issues is repeating several names that are already in a group more than once.

Create a variable named call_on_weighted and use it to choose make five
random selections from students, but this time assign different probability values
that will determine how likely each student is to be selected. At least one student
should have a zero likelihood of being called on, and at least one student should
have a 30% likelihood of being called on. Distribute other probability values as you
choose, and in a comment, explain the p values you assigned to each student. Print
call_on_weighted.

In [19]:
call_on_weighted = np.random.choice(students,size=5,p = [0.00,.30,.10,.10,.05,.05,.05,.05,.05,.10,.10,.05])

 the values i assigned had to equal 1.0 or 100

# Generating a normal Distribution

Create a variable named bell_curve and assign it a random distribution for
which the mean (peak of the curve) is 10, the standard deviation is 5, and the size of
the returned array is 4 rows by 5 columns. Print bell_curv

In [20]:
bell_curve =  np.random.normal(loc=10,scale=5,size=(4,5))

In [21]:
print(bell_curve)

[[ 2.59734097 11.40936402 16.64743954 17.6846537   8.62939837]
 [14.26423078 -0.56808672 11.218583   -0.80812731  4.50576004]
 [ 8.16963283  5.26459016  3.01672224  9.14010519 14.16192147]
 [13.75439127 11.245269    9.99581142  7.95032356 11.85861729]]
