# Exercis 1.c Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In a code cell, create five variables containing random sample arrays to work with,
copying over the expressions you used for variables r_1 through r_5 in the
notebook for Exercise 1.B (NumPy Random).

In [105]:
r_1= np.random.random ((3,3))
r_2= np.random.randint(1,11, size = (3,3))
r_3=np.random.normal(loc=10, scale=2,size=(3,3))
r_4=np.random.randint(1,11,size=(3,3))
    
r_5=np.random.random((3,2))

## Permutations 

In [80]:
print(r_4)


['bug' 'dog' 'cat' 'bird']


In [81]:
np.random.shuffle(r_4)
print(r_4)
# gave me the same characters that was printed out just shuffled


['dog' 'cat' 'bird' 'bug']


Create a new variable named new_shuffle, and assign it the value of a random
permutation of r_4. Print new_shuffle, and then print r_4 again to compare
values

In [85]:
new_shuffle = np.random.permutation(r_4)

In [86]:
print(new_shuffle)

['dog' 'cat' 'bird' 'bug']


In [84]:
print(r_4)

['dog' 'cat' 'bird' 'bug']


# permutation creates a shuffled copy of r_4 ,shuffle doesnt not change the original array

## Mathematical Operations

Print r_1 and r_2 as starting values, and also print the shape of each using the
.shape attribute. Then print the result of r_1 plus r_2, using the add function. Also
print the shape of the result

In [87]:
print(r_1)
print(r_2)

[[0.53692341 0.68044524 0.11911069]
 [0.97527964 0.35981718 0.14162065]]
[[10  5  1]
 [ 9  7  5]
 [ 9  2  6]]


In [90]:
print(r_1.shape)
print(r_2.shape)

(2, 3)
(3, 3)


In [94]:
result = np.add(r_1,r_2)
print(result)

[[ 8.60279168  1.19044042 10.27899283]
 [ 9.92944275  1.72588599  2.44984167]
 [ 2.48727045  2.80503002  8.37018098]]


In [95]:
print(result.shape)

(3, 3)


Print r_1 and r_3 as starting values, and also print the shape of each using the
.shape attribute. Then print the result of r_1 plus r_3, using the add function. Also
print the shape of the result

In [96]:
print(r_1)
print(r_3)

[[0.60279168 0.19044042 0.27899283]
 [0.92944275 0.72588599 0.44984167]
 [0.48727045 0.80503002 0.37018098]]
[[ 9.80639395 12.3309465   9.52608107  9.60814506]
 [13.1804929  12.83330858 11.01221107 11.69986298]]


In [99]:
print(r_1.shape)
print(r_3.shape)

(3, 3)
(3, 3)


In [100]:
result_2 = np.add(r_1,r_3)

In [101]:
print(result_2)

[[ 9.48612671 12.36438689 10.81329095]
 [ 4.74485775 13.52565658 14.43499833]
 [ 9.77048692 12.21776076 10.43803485]]


In [102]:
print(result_2.shape)

(3, 3)


Print r_2 and r_4 again as starting values, and also print the shape of each using
the .shape attribute. Then print the result of r_2 plus r_4, using the add function.
Also print the shape of the result

In [103]:
print(r_2)
print(r_4)

[[ 3  5  8]
 [ 1 10  5]
 [ 3  9  3]]
['dog' 'bird' 'cat' 'bird']


In [106]:
print(r_2.shape)
print(r_4.shape)

(3, 3)
(3, 3)


In [111]:
results_3 = np.add(r_2,r_4)

In [112]:
print(results_3)

[[ 6  9 11]
 [13  8 15]
 [ 8  8 15]]


In [113]:
print(results_3.shape)

(3, 3)


In [118]:
print(r_1 + r_4)

[[4.66043849 8.05842665 3.20510535]
 [4.12447881 6.08867298 5.38572271]
 [4.06464012 5.43218935 8.66194485]]


ValueError: operands could not be broadcast together with shapes,had to change

In [119]:
print(r_2 + r_4)

[[ 6  9 11]
 [13  8 15]
 [ 8  8 15]]


 also gives broadcasting error

Show what happens if you add np.array([1]) to r_4.

In [120]:
print(np.array([1]) + 4)

[5]


Show what happens if you add np.array([[1]]) to r_4.

In [122]:
print(np.array([[1]]) + r_4)

[[5 9 4]
 [5 7 6]
 [5 6 9]]


Show what happens if you add np.array([1,1,1,1,1]) to r_4.

In [124]:
print(np.array([1,1,1,1,1]) + r_4)

ValueError: operands could not be broadcast together with shapes (5,) (3,3) 

error ;operands could not be broadcast together with shapes (5,) (3,3) 

What happens if you add np.array([[1],[1]]) to r_4? Add a comment to the
cell with the error message this produces

In [125]:
print(np.array([[1],[1]]) + r_4)

ValueError: operands could not be broadcast together with shapes (2,1) (3,3) 

ValueError: operands could not be broadcast together with shapes (2,1) (3,3) 

for broadcasting to work the array dimensions need to be similar,usally equal dimensions

# Rounding

Print r_3 to display the values you’ll be working with for the next few cells.

In [126]:
print(r_3)

[[11.99976757 13.77582894 10.03584203]
 [10.45603819  9.35243091  9.80746505]
 [ 9.33542119 12.21026626  7.6767125 ]]


Round the values in r_3 using trunc.

In [128]:
print(np.trunc(r_3))

[[11. 13. 10.]
 [10.  9.  9.]
 [ 9. 12.  7.]]


Round the values in r_3 using fix.

In [129]:
print(np.fix(r_3))

[[11. 13. 10.]
 [10.  9.  9.]
 [ 9. 12.  7.]]


Round the values in r_3 using floor.

In [130]:
print(np.floor(r_3))

[[11. 13. 10.]
 [10.  9.  9.]
 [ 9. 12.  7.]]


In [131]:
print(np.ceil(r_3))

[[12. 14. 11.]
 [11. 10. 10.]
 [10. 13.  8.]]


Round the values in r_3 using round, to 2 decimal places.

In [132]:
print(np.round(r_3,2))

[[12.   13.78 10.04]
 [10.46  9.35  9.81]
 [ 9.34 12.21  7.68]]


## Cumultavie Operations

Print r_4 to display the values you’ll be working with for the next few cells

In [133]:
print(r_4)

[[4 8 3]
 [4 6 5]
 [4 5 8]]


Print the sum of all values in r_4.

In [135]:
print(np.sum(r_4))

47


Print the sum of elements along the 0 axis for r_4.

In [136]:
print(np.sum(r_4,axis=0))

[12 19 16]


Print the sum of elements along the 1 axis for r_4.

In [137]:
print(np.sum(r_4,axis=1))

[15 15 17]


Print the cumulative sum (rolling total) of values in r_

In [138]:
print(np.cumsum(r_4))

[ 4 12 15 19 25 30 34 39 47]


In [139]:
print(np.cumsum(r_4,axis=0))

[[ 4  8  3]
 [ 8 14  8]
 [12 19 16]]


# Grocery Problem

Create two new variables, bag1 and bag2. The first variable represents the
contents of a grocery bag, which contains two vegetables, three fruits, four boxes of
snacks, and no beverages. The second variable represents another grocery bag,
which contains no fruits, four vegetables, two beverages, and one box of snacks.
Assign an appropriate array to each variable that represents how many of each
category of item are in each bag. Print bag1 and bag2.

In [140]:
bag_1 = np.array([2,3,4,0])

bag_2 = np.array([4,0,1,2])


In [141]:
print(bag_1)
print(bag_2)

[2 3 4 0]
[4 0 1 2]


Write an expression to calculate the total number of items in each bag, and print the
result in the form of a sentence: The first bag contains __ items, and the second bag
contains ___ items.

In [147]:
print(f'The first bag contains {total_bag_1} intems, and the second bag contains {total_bag_2} items')

The first bag contains 9 intems, and the second bag contains 7 items


Write an expression to calculate the total number of items in each category, and
print the result in the form of a sentence: There are __ vegetables, __ fruits, __ boxes
of snacks, and __ beverages in the two grocery bags

In [148]:
total_grocery =  np.add(bag_1,bag_2)

In [149]:
print(total_grocery)

[6 3 5 2]


In [152]:
print(f' There are {total_grocery[0]} vegetables,{total_grocery[1]} fruits, {total_grocery[2]} boxes of snacks, {total_grocery[3]} beverages in the two grocery bags')

 There are 6 vegetables,3 fruits, 5 boxes of snacks, 2 beverages in the two grocery bags


## Teamwork

Ali reported knocking on 5 doors on Monday, 4 on Tuesday, 6 on Wednesday, 4 on
Thursday, and 2 on Friday. Create a variable holding an array of these value

In [162]:
ali = np.array([5,4,6,4,2])

Ben missed Monday because he was out of town. He reported knocking on 5 on
Tuesday, 5 on Wednesday, 3 on Thursday, and 4 on Friday. Create a variable holding
an array of Ben’s values.

In [163]:
ben = np.array([0,5,5,3,4])

Carla reported knocking on 3 doors on Monday, 6 on Tuesday, 3 on Thursday, and 4
on Friday. She was sick on Wednesday so missed that day. Create a variable
holding an array of Carla’s values.

In [164]:
carla = np.array([3,6,0,3,4])

In [165]:
all_knocks =np.add(np.add(ali,ben),carla)

In [166]:
print(all_knocks)

[ 8 15 11 10 10]


In [167]:
rolling_knocks = np.cumsum(all_knocks)

In [168]:
print(rolling_knocks)

[ 8 23 34 44 54]


In [169]:
est_votes = rolling_knocks * 0.5

In [170]:
print(est_votes)

[ 4.  11.5 17.  22.  27. ]
